version: '3'
services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    volumes:
      - ./auth_service:/app
    ports:
      - "3001:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=auth_service_development
      - AUTH_SERVICE_URL=http://auth_service:3000
      - NOTIFICATION_SERVICE_URL=http://notification_service:3000
      - SCRAPING_SERVICE_URL=http://scraping_service:3000
    depends_on:
      - db

  notification_service:
    build: ./notification_service
    container_name: notification_service
    volumes:
      - ./notification_service:/app
    ports:
      - "3002:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=notification_service_development
      - AUTH_SERVICE_URL=http://auth_service:3000
      - NOTIFICATION_SERVICE_URL=http://notification_service:3000
      - SCRAPING_SERVICE_URL=http://scraping_service:3000
    depends_on:
      - db

  scraping_service:
    build: ./scraping_service
    container_name: scraping_service
    volumes:
      - ./scraping_service:/app
    ports:
      - "3003:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=scraping_service_development
      - AUTH_SERVICE_URL=http://auth_service:3000
      - NOTIFICATION_SERVICE_URL=http://notification_service:3000
      - SCRAPING_SERVICE_URL=http://scraping_service:3000
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  task_management:
    build: ./task_management
    container_name: task_management
    volumes:
      - ./task_management:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=task_management_development
      - AUTH_SERVICE_URL=http://auth_service:3000
      - NOTIFICATION_SERVICE_URL=http://notification_service:3000
      - SCRAPING_SERVICE_URL=http://scraping_service:3000
    depends_on:
      - db
      - auth_service
      - notification_service
      - scraping_service

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  sidekiq:
    build: ./scraping_service
    command: bundle exec sidekiq
    volumes:
      - ./scraping_service:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=scraping_service_development
    depends_on:
      - redis
      - scraping_service
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: development
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
