production:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: notification_service_production

development:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: notification_service_development
